language: cpp

os:
  - linux
  #- osx

compiler:
  #- clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lcov
      - valgrind

  apt_packages:
    - swig3.0

before_script:
  - mkdir build
  - pushd build
  - export CODECOV_TOKEN="e17b0bb1-d93e-40de-b62b-9b7193459821"

before_install:
  - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install swig valgrind lcov libomp
    fi

script:
  - cmake -DUSE_SWIG=ON -DUSE_GTEST=ON -DUSE_GCOV=ON ..
#  - make _feasst
  - make
  - make coverage
#  - make install
#  - make test
  - valgrind ./bin/unittest
#  - python ../py/test.py
  - ../py/run.sh ../py/test.py

after_success:
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
